[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
    'npm install --force --no-audit --no-fund',
    'cd smart-city-traveler-frontend && npm install --force --no-audit --no-fund'
]

[phases.build]
cmds = [
    'cd smart-city-traveler-frontend && npm run build'
]

[start]
cmd = 'node server.js'